# Generated by Django 6.0.3 on 2026-04-05 11:01

from django.db import migrations


def create_default_teams(apps, schema_editor):
    Team = apps.get_model('scores', 'Team')
    
    default_teams = [
        {'name': 'Red Team', 'color': 'red'},
        {'name': 'Blue Team', 'color': 'blue'},
        {'name': 'Green Team', 'color': 'green'},
        {'name': 'Yellow Team', 'color': 'yellow'},
        {'name': 'Orange Team', 'color': 'orange'},
        {'name': 'Purple Team', 'color': 'purple'},
        {'name': 'Pink Team', 'color': 'pink'},
    ]
    
    for team_data in default_teams:
        Team.objects.get_or_create(
            name=team_data['name'],
            color=team_data['color']
        )


def reverse_create_default_teams(apps, schema_editor):
    Team = apps.get_model('scores', 'Team')
    
    default_teams = [
        'Red Team', 'Blue Team', 'Green Team', 'Yellow Team',
        'Orange Team', 'Purple Team', 'Pink Team'
    ]
    
    Team.objects.filter(name__in=default_teams).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_teams, reverse_create_default_teams),
    ]
