# Generated by Django migration

from django.db import migrations, models


def create_default_colors(apps, schema_editor):
    TeamColor = apps.get_model('scores', 'TeamColor')
    default_colors = [
        {'name': 'Red', 'color_code': '#ef4444'},
        {'name': 'Blue', 'color_code': '#3b82f6'},
        {'name': 'Green', 'color_code': '#10b981'},
        {'name': 'Yellow', 'color_code': '#eab308'},
        {'name': 'Orange', 'color_code': '#f97316'},
        {'name': 'Purple', 'color_code': '#a855f7'},
        {'name': 'Pink', 'color_code': '#ec4899'},
    ]
    
    for color_data in default_colors:
        TeamColor.objects.create(**color_data)


def update_existing_teams(apps, schema_editor):
    Team = apps.get_model('scores', 'Team')
    TeamColor = apps.get_model('scores', 'TeamColor')
    
    # Get teams that have the old color field (not the new temp field)
    for team in Team.objects.all():
        if hasattr(team, 'color') and team.color and not hasattr(team, 'color_temp'):
            color_name = team.color
            try:
                color_obj = TeamColor.objects.get(name=color_name.title())
                team.color_temp = color_obj
                team.save()
            except TeamColor.DoesNotExist:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_auto_20260405_1901'),
    ]

    operations = [
        # Create TeamColor model
        migrations.CreateModel(
            name='TeamColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('color_code', models.CharField(max_length=7, verbose_name='Color code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Team Color',
                'verbose_name_plural': 'Team Colors',
                'ordering': ['name'],
            },
        ),
        
        # Add temporary foreign key field
        migrations.AddField(
            model_name='team',
            name='color_temp',
            field=models.ForeignKey(
                'scores.TeamColor', 
                on_delete=models.PROTECT, 
                related_name='teams',
                null=True,
                blank=True
            ),
        ),
        
        # Populate colors and update teams
        migrations.RunPython(create_default_colors),
        migrations.RunPython(update_existing_teams),
        
        # Remove old field
        migrations.RemoveField(
            model_name='team',
            name='color',
        ),
        
        # Rename temporary field
        migrations.RenameField(
            model_name='team',
            old_name='color_temp',
            new_name='color',
        ),
    ]
