# Generated by Django 6.0.3 on 2026-04-05 12:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_teamcolor_alter_team_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamcolor',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='scoreentry',
            name='points',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='team',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='scores.teamcolor'),
        ),
        migrations.AlterField(
            model_name='teamcolor',
            name='color_code',
            field=models.CharField(help_text='Hex color code (e.g., #FF0000)', max_length=7),
        ),
        migrations.AlterField(
            model_name='teamcolor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teamcolor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teamcolor',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
